apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.fullname" . }}-svc
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.application.config.port }}
      targetPort: {{ .Values.application.config.port }}
      name: http
  selector:
    {{- include "gateway.selectorLabels" . | nindent 4 }}
