apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eureka.fullname" . }}-deployment
  labels:
    {{- include "eureka.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "eureka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eureka.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          ports:
            - name: http
              containerPort: {{ .Values.application.config.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "eureka.fullname" . }}-cm
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.application.config.port }}
